### ISSUE TITLE
OpenVINO docker

### ISSUE THREAD

**Issue by buaapengbo** [muka/openvino-docker#1]
Hi, 

May I ask you, have you already done dockerization of OpenVINO?

Thanks
Bo

**Comment by muka** [comment]
Hi
yes I did it but is not public. Basically you have to collect all the `.so` libraries you need in a directory and pass to the container and set your global variables accordingly (eg `LD_LIBRARY_PATH`) depending on your requirments.

You can follow the env script in the openvino installation to have guidance of the required libs.

I have not been able to run docker without the `privileged` flag tough

**Comment by buaapengbo** [comment]
Hi, I will try that, thanks
